spring:
  application:
    name: GreengramVer3
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_tdd
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 5MB
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: redraib05@gmail.com
    password: sgmosqfnfffcbhwk
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7



mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger # Swagger page? redirect
    operations-sorter: method # default : alpha -> url ???? ???
    default-model-expand-depth: 10
    default-models-expand-depth: 10
    display-request-duration: true # try it out ? ??? request duration(?? ????)? ??? ???
  cache:
    disabled: true

file:
  directory: D:\download\greengram_tdd\

---

spring:
  config:
   activate:
     on-profile: tdd
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_tdd_test
  sql:
    init:
      mode: always